name: Unit test

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/*'
      - 'test/*'
      - '*.toml'
  push:
    branches: [ master ]
    paths:
      - 'src/*'
      - 'test/*'
      - '*.toml'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.threads }} thread(s)
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: ${{ matrix.threads }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'nightly'
        os:
          - ubuntu-latest
        threads:
          - '1'
          - '2'
        arch:
          - x64

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@latest